namespace ATABBI.TexE
{
    partial class Toolbox
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code
        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Toolbox));
            this.imageList = new System.Windows.Forms.ImageList(this.components);
            this.toolBox1 = new VS2005ToolBox.ToolBox();
            this.SuspendLayout();
            // 
            // imageList
            // 
            this.imageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList.ImageStream")));
            this.imageList.TransparentColor = System.Drawing.Color.Transparent;
            this.imageList.Images.SetKeyName(0, "Mouse.bmp");
            this.imageList.Images.SetKeyName(1, "alpha_L.png");
            this.imageList.Images.SetKeyName(2, "amalg_L.png");
            this.imageList.Images.SetKeyName(3, "angle_L.png");
            this.imageList.Images.SetKeyName(4, "approx_L.png");
            this.imageList.Images.SetKeyName(5, "approxeq_L.png");
            this.imageList.Images.SetKeyName(6, "arccos_L.png");
            this.imageList.Images.SetKeyName(7, "arcsin_L.png");
            this.imageList.Images.SetKeyName(8, "arctan_L.png");
            this.imageList.Images.SetKeyName(9, "arg_L.png");
            this.imageList.Images.SetKeyName(10, "ast_L.png");
            this.imageList.Images.SetKeyName(11, "asymp_L.png");
            this.imageList.Images.SetKeyName(12, "backepsilon_L.png");
            this.imageList.Images.SetKeyName(13, "backprime_L.png");
            this.imageList.Images.SetKeyName(14, "backsim_L.png");
            this.imageList.Images.SetKeyName(15, "backsimeq_L.png");
            this.imageList.Images.SetKeyName(16, "barwedge_L.png");
            this.imageList.Images.SetKeyName(17, "because_L.png");
            this.imageList.Images.SetKeyName(18, "beta_L.png");
            this.imageList.Images.SetKeyName(19, "between_L.png");
            this.imageList.Images.SetKeyName(20, "bigcap_L.png");
            this.imageList.Images.SetKeyName(21, "bigcirc_L.png");
            this.imageList.Images.SetKeyName(22, "bigcup_L.png");
            this.imageList.Images.SetKeyName(23, "bigodot_L.png");
            this.imageList.Images.SetKeyName(24, "bigoplus_L.png");
            this.imageList.Images.SetKeyName(25, "bigotimes_L.png");
            this.imageList.Images.SetKeyName(26, "bigsqcup_L.png");
            this.imageList.Images.SetKeyName(27, "bigstar_L.png");
            this.imageList.Images.SetKeyName(28, "bigtriangledown_L.png");
            this.imageList.Images.SetKeyName(29, "bigtriangleup_L.png");
            this.imageList.Images.SetKeyName(30, "biguplus_L.png");
            this.imageList.Images.SetKeyName(31, "bigvee_L.png");
            this.imageList.Images.SetKeyName(32, "bigwedge_L.png");
            this.imageList.Images.SetKeyName(33, "blacklozenge_L.png");
            this.imageList.Images.SetKeyName(34, "blacksquare_L.png");
            this.imageList.Images.SetKeyName(35, "blacktriangle_L.png");
            this.imageList.Images.SetKeyName(36, "blacktriangledown_L.png");
            this.imageList.Images.SetKeyName(37, "blacktriangleleft_L.png");
            this.imageList.Images.SetKeyName(38, "blacktriangleright_L.png");
            this.imageList.Images.SetKeyName(39, "bot_L.png");
            this.imageList.Images.SetKeyName(40, "bowtie_L.png");
            this.imageList.Images.SetKeyName(41, "boxdot_L.png");
            this.imageList.Images.SetKeyName(42, "boxminus_L.png");
            this.imageList.Images.SetKeyName(43, "boxplus_L.png");
            this.imageList.Images.SetKeyName(44, "boxtimes_L.png");
            this.imageList.Images.SetKeyName(45, "bullet_L.png");
            this.imageList.Images.SetKeyName(46, "bumpeq_L.png");
            this.imageList.Images.SetKeyName(47, "Bumpeq_U.png");
            this.imageList.Images.SetKeyName(48, "cap_L.png");
            this.imageList.Images.SetKeyName(49, "Cap_U.png");
            this.imageList.Images.SetKeyName(50, "cdot_L.png");
            this.imageList.Images.SetKeyName(51, "centerdot_L.png");
            this.imageList.Images.SetKeyName(52, "chi_L.png");
            this.imageList.Images.SetKeyName(53, "circ_L.png");
            this.imageList.Images.SetKeyName(54, "circeq_L.png");
            this.imageList.Images.SetKeyName(55, "circlearrowleft_L.png");
            this.imageList.Images.SetKeyName(56, "circlearrowright_L.png");
            this.imageList.Images.SetKeyName(57, "circledast_L.png");
            this.imageList.Images.SetKeyName(58, "circledcirc_L.png");
            this.imageList.Images.SetKeyName(59, "circleddash_L.png");
            this.imageList.Images.SetKeyName(60, "clubsuit_L.png");
            this.imageList.Images.SetKeyName(61, "cong_L.png");
            this.imageList.Images.SetKeyName(62, "coprod_L.png");
            this.imageList.Images.SetKeyName(63, "cos_L.png");
            this.imageList.Images.SetKeyName(64, "cosh_L.png");
            this.imageList.Images.SetKeyName(65, "cot_L.png");
            this.imageList.Images.SetKeyName(66, "coth_L.png");
            this.imageList.Images.SetKeyName(67, "csc_L.png");
            this.imageList.Images.SetKeyName(68, "cup_L.png");
            this.imageList.Images.SetKeyName(69, "Cup_U.png");
            this.imageList.Images.SetKeyName(70, "curlyeqprec_L.png");
            this.imageList.Images.SetKeyName(71, "curlyeqsucc_L.png");
            this.imageList.Images.SetKeyName(72, "curlyvee_L.png");
            this.imageList.Images.SetKeyName(73, "curlywedge_L.png");
            this.imageList.Images.SetKeyName(74, "curvearrowleft_L.png");
            this.imageList.Images.SetKeyName(75, "curvearrowright_L.png");
            this.imageList.Images.SetKeyName(76, "dagger_L.png");
            this.imageList.Images.SetKeyName(77, "dashv_L.png");
            this.imageList.Images.SetKeyName(78, "ddagger_L.png");
            this.imageList.Images.SetKeyName(79, "deg_L.png");
            this.imageList.Images.SetKeyName(80, "delta_L.png");
            this.imageList.Images.SetKeyName(81, "det_L.png");
            this.imageList.Images.SetKeyName(82, "diagdown_L.png");
            this.imageList.Images.SetKeyName(83, "diagup_L.png");
            this.imageList.Images.SetKeyName(84, "diamond_L.png");
            this.imageList.Images.SetKeyName(85, "diamondsuit_L.png");
            this.imageList.Images.SetKeyName(86, "digamma_L.png");
            this.imageList.Images.SetKeyName(87, "dim_L.png");
            this.imageList.Images.SetKeyName(88, "div_L.png");
            this.imageList.Images.SetKeyName(89, "divideontimes_L.png");
            this.imageList.Images.SetKeyName(90, "doteq_L.png");
            this.imageList.Images.SetKeyName(91, "doteqdot_L.png");
            this.imageList.Images.SetKeyName(92, "dotplus_L.png");
            this.imageList.Images.SetKeyName(93, "doublebarwedge_L.png");
            this.imageList.Images.SetKeyName(94, "downdownarrows_L.png");
            this.imageList.Images.SetKeyName(95, "downharpoonleft_L.png");
            this.imageList.Images.SetKeyName(96, "downharpoonright_L.png");
            this.imageList.Images.SetKeyName(97, "emptyset_L.png");
            this.imageList.Images.SetKeyName(98, "epsilon_L.png");
            this.imageList.Images.SetKeyName(99, "eqcirc_L.png");
            this.imageList.Images.SetKeyName(100, "eqsim_L.png");
            this.imageList.Images.SetKeyName(101, "eqslantgtr_L.png");
            this.imageList.Images.SetKeyName(102, "eqslantless_L.png");
            this.imageList.Images.SetKeyName(103, "equiv_L.png");
            this.imageList.Images.SetKeyName(104, "eta_L.png");
            this.imageList.Images.SetKeyName(105, "exists_L.png");
            this.imageList.Images.SetKeyName(106, "exp_L.png");
            this.imageList.Images.SetKeyName(107, "fallingdotseq_L.png");
            this.imageList.Images.SetKeyName(108, "flat_L.png");
            this.imageList.Images.SetKeyName(109, "forall_L.png");
            this.imageList.Images.SetKeyName(110, "frown_L.png");
            this.imageList.Images.SetKeyName(111, "gamma_L.png");
            this.imageList.Images.SetKeyName(112, "gcd_L.png");
            this.imageList.Images.SetKeyName(113, "geq_L.png");
            this.imageList.Images.SetKeyName(114, "geqq_L.png");
            this.imageList.Images.SetKeyName(115, "geqslant_L.png");
            this.imageList.Images.SetKeyName(116, "gg_L.png");
            this.imageList.Images.SetKeyName(117, "ggg_L.png");
            this.imageList.Images.SetKeyName(118, "gnapprox_L.png");
            this.imageList.Images.SetKeyName(119, "gneq_L.png");
            this.imageList.Images.SetKeyName(120, "gneqq_L.png");
            this.imageList.Images.SetKeyName(121, "gnsim_L.png");
            this.imageList.Images.SetKeyName(122, "gtrapprox_L.png");
            this.imageList.Images.SetKeyName(123, "gtrdot_L.png");
            this.imageList.Images.SetKeyName(124, "gtreqless_L.png");
            this.imageList.Images.SetKeyName(125, "gtreqqless_L.png");
            this.imageList.Images.SetKeyName(126, "gtrless_L.png");
            this.imageList.Images.SetKeyName(127, "gtrsim_L.png");
            this.imageList.Images.SetKeyName(128, "gvertneqq_L.png");
            this.imageList.Images.SetKeyName(129, "heartsuit_L.png");
            this.imageList.Images.SetKeyName(130, "hom_L.png");
            this.imageList.Images.SetKeyName(131, "hookleftarrow_L.png");
            this.imageList.Images.SetKeyName(132, "hookrightarrow_L.png");
            this.imageList.Images.SetKeyName(133, "in_L.png");
            this.imageList.Images.SetKeyName(134, "inf_L.png");
            this.imageList.Images.SetKeyName(135, "infty_L.png");
            this.imageList.Images.SetKeyName(136, "injlim_L.png");
            this.imageList.Images.SetKeyName(137, "int_L.png");
            this.imageList.Images.SetKeyName(138, "intercal_L.png");
            this.imageList.Images.SetKeyName(139, "iota_L.png");
            this.imageList.Images.SetKeyName(140, "kappa_L.png");
            this.imageList.Images.SetKeyName(141, "ker_L.png");
            this.imageList.Images.SetKeyName(142, "lambda_L.png");
            this.imageList.Images.SetKeyName(143, "leftarrow_L.png");
            this.imageList.Images.SetKeyName(144, "Leftarrow_U.png");
            this.imageList.Images.SetKeyName(145, "leftarrowtail_L.png");
            this.imageList.Images.SetKeyName(146, "leftharpoondown_L.png");
            this.imageList.Images.SetKeyName(147, "leftharpoonup_L.png");
            this.imageList.Images.SetKeyName(148, "leftleftarrows_L.png");
            this.imageList.Images.SetKeyName(149, "leftrightarrow_L.png");
            this.imageList.Images.SetKeyName(150, "Leftrightarrow_U.png");
            this.imageList.Images.SetKeyName(151, "leftrightarrows_L.png");
            this.imageList.Images.SetKeyName(152, "leftrightharpoons_L.png");
            this.imageList.Images.SetKeyName(153, "leftrightsquigarrow_L.png");
            this.imageList.Images.SetKeyName(154, "leftthreetimes_L.png");
            this.imageList.Images.SetKeyName(155, "leq_L.png");
            this.imageList.Images.SetKeyName(156, "leqq_L.png");
            this.imageList.Images.SetKeyName(157, "leqslant_L.png");
            this.imageList.Images.SetKeyName(158, "lessapprox_L.png");
            this.imageList.Images.SetKeyName(159, "lessdot_L.png");
            this.imageList.Images.SetKeyName(160, "lesseqgtr_L.png");
            this.imageList.Images.SetKeyName(161, "lesseqqgtr_L.png");
            this.imageList.Images.SetKeyName(162, "lessgtr_L.png");
            this.imageList.Images.SetKeyName(163, "lesssim_L.png");
            this.imageList.Images.SetKeyName(164, "lg_L.png");
            this.imageList.Images.SetKeyName(165, "lim_L.png");
            this.imageList.Images.SetKeyName(166, "liminf_L.png");
            this.imageList.Images.SetKeyName(167, "limsup_L.png");
            this.imageList.Images.SetKeyName(168, "ll_L.png");
            this.imageList.Images.SetKeyName(169, "Lleftarrow_U.png");
            this.imageList.Images.SetKeyName(170, "lll_L.png");
            this.imageList.Images.SetKeyName(171, "ln_L.png");
            this.imageList.Images.SetKeyName(172, "lnapprox_L.png");
            this.imageList.Images.SetKeyName(173, "lneq_L.png");
            this.imageList.Images.SetKeyName(174, "lneqq_L.png");
            this.imageList.Images.SetKeyName(175, "lnsim_L.png");
            this.imageList.Images.SetKeyName(176, "log_L.png");
            this.imageList.Images.SetKeyName(177, "longleftarrow_L.png");
            this.imageList.Images.SetKeyName(178, "Longleftarrow_U.png");
            this.imageList.Images.SetKeyName(179, "longleftrightarrow_L.png");
            this.imageList.Images.SetKeyName(180, "Longleftrightarrow_U.png");
            this.imageList.Images.SetKeyName(181, "longmapsto_L.png");
            this.imageList.Images.SetKeyName(182, "longrightarrow_L.png");
            this.imageList.Images.SetKeyName(183, "Longrightarrow_U.png");
            this.imageList.Images.SetKeyName(184, "looparrowleft_L.png");
            this.imageList.Images.SetKeyName(185, "looparrowright_L.png");
            this.imageList.Images.SetKeyName(186, "lozenge_L.png");
            this.imageList.Images.SetKeyName(187, "Lsh_U.png");
            this.imageList.Images.SetKeyName(188, "ltimes_L.png");
            this.imageList.Images.SetKeyName(189, "lvertneqq_L.png");
            this.imageList.Images.SetKeyName(190, "mapsto_L.png");
            this.imageList.Images.SetKeyName(191, "max_L.png");
            this.imageList.Images.SetKeyName(192, "measuredangle_L.png");
            this.imageList.Images.SetKeyName(193, "mid_L.png");
            this.imageList.Images.SetKeyName(194, "min_L.png");
            this.imageList.Images.SetKeyName(195, "models_L.png");
            this.imageList.Images.SetKeyName(196, "mp_L.png");
            this.imageList.Images.SetKeyName(197, "mu_L.png");
            this.imageList.Images.SetKeyName(198, "multimap_L.png");
            this.imageList.Images.SetKeyName(199, "nabla_L.png");
            this.imageList.Images.SetKeyName(200, "natural_L.png");
            this.imageList.Images.SetKeyName(201, "ncong_L.png");
            this.imageList.Images.SetKeyName(202, "nearrow_L.png");
            this.imageList.Images.SetKeyName(203, "neg_L.png");
            this.imageList.Images.SetKeyName(204, "neq_L.png");
            this.imageList.Images.SetKeyName(205, "nexists_L.png");
            this.imageList.Images.SetKeyName(206, "ngeq_L.png");
            this.imageList.Images.SetKeyName(207, "ngeqq_L.png");
            this.imageList.Images.SetKeyName(208, "ngeqslant_L.png");
            this.imageList.Images.SetKeyName(209, "ngtr_L.png");
            this.imageList.Images.SetKeyName(210, "ni_L.png");
            this.imageList.Images.SetKeyName(211, "nLeftarrow_L.png");
            this.imageList.Images.SetKeyName(212, "nLeftrightarrow_L.png");
            this.imageList.Images.SetKeyName(213, "nleq_L.png");
            this.imageList.Images.SetKeyName(214, "nleqq_L.png");
            this.imageList.Images.SetKeyName(215, "nleqslant_L.png");
            this.imageList.Images.SetKeyName(216, "nless_L.png");
            this.imageList.Images.SetKeyName(217, "nmid_L.png");
            this.imageList.Images.SetKeyName(218, "notin_L.png");
            this.imageList.Images.SetKeyName(219, "nparallel_L.png");
            this.imageList.Images.SetKeyName(220, "nprec_L.png");
            this.imageList.Images.SetKeyName(221, "npreceq_L.png");
            this.imageList.Images.SetKeyName(222, "nRightarrow_L.png");
            this.imageList.Images.SetKeyName(223, "nshortmid_L.png");
            this.imageList.Images.SetKeyName(224, "nshortparallel_L.png");
            this.imageList.Images.SetKeyName(225, "nsim_L.png");
            this.imageList.Images.SetKeyName(226, "nsubseteq_L.png");
            this.imageList.Images.SetKeyName(227, "nsubseteqq_L.png");
            this.imageList.Images.SetKeyName(228, "nsucc_L.png");
            this.imageList.Images.SetKeyName(229, "nsucceq_L.png");
            this.imageList.Images.SetKeyName(230, "nsupseteq_L.png");
            this.imageList.Images.SetKeyName(231, "nsupseteqq_L.png");
            this.imageList.Images.SetKeyName(232, "ntriangleleft_L.png");
            this.imageList.Images.SetKeyName(233, "ntrianglelefteq_L.png");
            this.imageList.Images.SetKeyName(234, "ntriangleright_L.png");
            this.imageList.Images.SetKeyName(235, "ntrianglerighteq_L.png");
            this.imageList.Images.SetKeyName(236, "nu_L.png");
            this.imageList.Images.SetKeyName(237, "nvdash_L.png");
            this.imageList.Images.SetKeyName(238, "nwarrow_L.png");
            this.imageList.Images.SetKeyName(239, "odot_L.png");
            this.imageList.Images.SetKeyName(240, "oint_L.png");
            this.imageList.Images.SetKeyName(241, "omega_L.png");
            this.imageList.Images.SetKeyName(242, "Omega_U.png");
            this.imageList.Images.SetKeyName(243, "ominus_L.png");
            this.imageList.Images.SetKeyName(244, "oplus_L.png");
            this.imageList.Images.SetKeyName(245, "oslash_L.png");
            this.imageList.Images.SetKeyName(246, "otimes_L.png");
            this.imageList.Images.SetKeyName(247, "parallel_L.png");
            this.imageList.Images.SetKeyName(248, "perp_L.png");
            this.imageList.Images.SetKeyName(249, "phi_L.png");
            this.imageList.Images.SetKeyName(250, "Phi_U.png");
            this.imageList.Images.SetKeyName(251, "pi_L.png");
            this.imageList.Images.SetKeyName(252, "Pi_U.png");
            this.imageList.Images.SetKeyName(253, "pitchfork_L.png");
            this.imageList.Images.SetKeyName(254, "pm_L.png");
            this.imageList.Images.SetKeyName(255, "Pr_U.png");
            this.imageList.Images.SetKeyName(256, "prec_L.png");
            this.imageList.Images.SetKeyName(257, "precapprox_L.png");
            this.imageList.Images.SetKeyName(258, "preccurlyeq_L.png");
            this.imageList.Images.SetKeyName(259, "preceq_L.png");
            this.imageList.Images.SetKeyName(260, "precnapprox_L.png");
            this.imageList.Images.SetKeyName(261, "precneqq_L.png");
            this.imageList.Images.SetKeyName(262, "precnsim_L.png");
            this.imageList.Images.SetKeyName(263, "precsim_L.png");
            this.imageList.Images.SetKeyName(264, "prime_L.png");
            this.imageList.Images.SetKeyName(265, "prod_L.png");
            this.imageList.Images.SetKeyName(266, "projlim_L.png");
            this.imageList.Images.SetKeyName(267, "propto_L.png");
            this.imageList.Images.SetKeyName(268, "psi_L.png");
            this.imageList.Images.SetKeyName(269, "Psi_U.png");
            this.imageList.Images.SetKeyName(270, "rho_L.png");
            this.imageList.Images.SetKeyName(271, "rightarrow_L.png");
            this.imageList.Images.SetKeyName(272, "Rightarrow_U.png");
            this.imageList.Images.SetKeyName(273, "rightarrowtail_L.png");
            this.imageList.Images.SetKeyName(274, "rightharpoondown_L.png");
            this.imageList.Images.SetKeyName(275, "rightharpoonup_L.png");
            this.imageList.Images.SetKeyName(276, "rightleftarrows_L.png");
            this.imageList.Images.SetKeyName(277, "rightleftharpoons_L.png");
            this.imageList.Images.SetKeyName(278, "rightrightarrows_L.png");
            this.imageList.Images.SetKeyName(279, "rightsquigarrow_L.png");
            this.imageList.Images.SetKeyName(280, "rightthreetimes_L.png");
            this.imageList.Images.SetKeyName(281, "risingdotseq_L.png");
            this.imageList.Images.SetKeyName(282, "Rrightarrow_U.png");
            this.imageList.Images.SetKeyName(283, "Rsh_U.png");
            this.imageList.Images.SetKeyName(284, "rtimes_L.png");
            this.imageList.Images.SetKeyName(285, "searrow_L.png");
            this.imageList.Images.SetKeyName(286, "sec_L.png");
            this.imageList.Images.SetKeyName(287, "setminus_L.png");
            this.imageList.Images.SetKeyName(288, "sharp_L.png");
            this.imageList.Images.SetKeyName(289, "shortmid_L.png");
            this.imageList.Images.SetKeyName(290, "shortparallel_L.png");
            this.imageList.Images.SetKeyName(291, "sigma_L.png");
            this.imageList.Images.SetKeyName(292, "Sigma_U.png");
            this.imageList.Images.SetKeyName(293, "sim_L.png");
            this.imageList.Images.SetKeyName(294, "simeq_L.png");
            this.imageList.Images.SetKeyName(295, "sin_L.png");
            this.imageList.Images.SetKeyName(296, "sinh_L.png");
            this.imageList.Images.SetKeyName(297, "smallfrown_L.png");
            this.imageList.Images.SetKeyName(298, "smallsetminus_L.png");
            this.imageList.Images.SetKeyName(299, "smallsmile_L.png");
            this.imageList.Images.SetKeyName(300, "smile_L.png");
            this.imageList.Images.SetKeyName(301, "spadesuit_L.png");
            this.imageList.Images.SetKeyName(302, "sphericalangle_L.png");
            this.imageList.Images.SetKeyName(303, "sqcap_L.png");
            this.imageList.Images.SetKeyName(304, "sqcup_L.png");
            this.imageList.Images.SetKeyName(305, "sqsubset_L.png");
            this.imageList.Images.SetKeyName(306, "sqsubseteq_L.png");
            this.imageList.Images.SetKeyName(307, "sqsupset_L.png");
            this.imageList.Images.SetKeyName(308, "sqsupseteq_L.png");
            this.imageList.Images.SetKeyName(309, "square p_L.png");
            this.imageList.Images.SetKeyName(310, "star_L.png");
            this.imageList.Images.SetKeyName(311, "subset_L.png");
            this.imageList.Images.SetKeyName(312, "Subset_U.png");
            this.imageList.Images.SetKeyName(313, "subseteq_L.png");
            this.imageList.Images.SetKeyName(314, "subseteqq_L.png");
            this.imageList.Images.SetKeyName(315, "subsetneq_L.png");
            this.imageList.Images.SetKeyName(316, "subsetneqq_L.png");
            this.imageList.Images.SetKeyName(317, "succ_L.png");
            this.imageList.Images.SetKeyName(318, "succapprox_L.png");
            this.imageList.Images.SetKeyName(319, "succcurlyeq_L.png");
            this.imageList.Images.SetKeyName(320, "succeq_L.png");
            this.imageList.Images.SetKeyName(321, "succnapprox_L.png");
            this.imageList.Images.SetKeyName(322, "succneqq_L.png");
            this.imageList.Images.SetKeyName(323, "succnsim_L.png");
            this.imageList.Images.SetKeyName(324, "succsim_L.png");
            this.imageList.Images.SetKeyName(325, "sum_L.png");
            this.imageList.Images.SetKeyName(326, "sup_L.png");
            this.imageList.Images.SetKeyName(327, "supset_L.png");
            this.imageList.Images.SetKeyName(328, "Supset_U.png");
            this.imageList.Images.SetKeyName(329, "supseteq_L.png");
            this.imageList.Images.SetKeyName(330, "supseteqq_L.png");
            this.imageList.Images.SetKeyName(331, "supsetneq_L.png");
            this.imageList.Images.SetKeyName(332, "supsetneqq_L.png");
            this.imageList.Images.SetKeyName(333, "surd_L.png");
            this.imageList.Images.SetKeyName(334, "swarrow_L.png");
            this.imageList.Images.SetKeyName(335, "tan_L.png");
            this.imageList.Images.SetKeyName(336, "tanh_L.png");
            this.imageList.Images.SetKeyName(337, "tau_L.png");
            this.imageList.Images.SetKeyName(338, "therefore_L.png");
            this.imageList.Images.SetKeyName(339, "theta_L.png");
            this.imageList.Images.SetKeyName(340, "Theta_U.png");
            this.imageList.Images.SetKeyName(341, "thickapprox_L.png");
            this.imageList.Images.SetKeyName(342, "thicksim_L.png");
            this.imageList.Images.SetKeyName(343, "times_L.png");
            this.imageList.Images.SetKeyName(344, "top_L.png");
            this.imageList.Images.SetKeyName(345, "triangle_L.png");
            this.imageList.Images.SetKeyName(346, "triangledown_L.png");
            this.imageList.Images.SetKeyName(347, "triangleleft_L.png");
            this.imageList.Images.SetKeyName(348, "trianglelefteq_L.png");
            this.imageList.Images.SetKeyName(349, "triangleq_L.png");
            this.imageList.Images.SetKeyName(350, "triangleright_L.png");
            this.imageList.Images.SetKeyName(351, "trianglerighteq_L.png");
            this.imageList.Images.SetKeyName(352, "twoheadleftarrow_L.png");
            this.imageList.Images.SetKeyName(353, "twoheadrightarrow_L.png");
            this.imageList.Images.SetKeyName(354, "upharpoonleft_L.png");
            this.imageList.Images.SetKeyName(355, "upharpoonright_L.png");
            this.imageList.Images.SetKeyName(356, "uplus_L.png");
            this.imageList.Images.SetKeyName(357, "upsilon_L.png");
            this.imageList.Images.SetKeyName(358, "Upsilon_U.png");
            this.imageList.Images.SetKeyName(359, "upuparrows_L.png");
            this.imageList.Images.SetKeyName(360, "varepsilon_L.png");
            this.imageList.Images.SetKeyName(361, "varinjlim_L.png");
            this.imageList.Images.SetKeyName(362, "varkappa_L.png");
            this.imageList.Images.SetKeyName(363, "varliminf_L.png");
            this.imageList.Images.SetKeyName(364, "varlimsup_L.png");
            this.imageList.Images.SetKeyName(365, "varnothing_L.png");
            this.imageList.Images.SetKeyName(366, "varphi_L.png");
            this.imageList.Images.SetKeyName(367, "varpi_L.png");
            this.imageList.Images.SetKeyName(368, "varprojlim_L.png");
            this.imageList.Images.SetKeyName(369, "varpropto_L.png");
            this.imageList.Images.SetKeyName(370, "varrho_L.png");
            this.imageList.Images.SetKeyName(371, "varsigma_L.png");
            this.imageList.Images.SetKeyName(372, "varsubsetneq_L.png");
            this.imageList.Images.SetKeyName(373, "varsubsetneqq_L.png");
            this.imageList.Images.SetKeyName(374, "varsupsetneq_L.png");
            this.imageList.Images.SetKeyName(375, "varsupsetneqq_L.png");
            this.imageList.Images.SetKeyName(376, "vartheta_L.png");
            this.imageList.Images.SetKeyName(377, "vartriangle_L.png");
            this.imageList.Images.SetKeyName(378, "vartriangleleft_L.png");
            this.imageList.Images.SetKeyName(379, "vartriangleright_L.png");
            this.imageList.Images.SetKeyName(380, "vdash_L.png");
            this.imageList.Images.SetKeyName(381, "Vdash_U.png");
            this.imageList.Images.SetKeyName(382, "vee_L.png");
            this.imageList.Images.SetKeyName(383, "veebar_L.png");
            this.imageList.Images.SetKeyName(384, "Vvdash_U.png");
            this.imageList.Images.SetKeyName(385, "wedge_L.png");
            this.imageList.Images.SetKeyName(386, "wr_L.png");
            this.imageList.Images.SetKeyName(387, "xi_L.png");
            this.imageList.Images.SetKeyName(388, "Xi_U.png");
            this.imageList.Images.SetKeyName(389, "zeta_L.png");
            // 
            // toolBox1
            // 
            this.toolBox1.BackColor = System.Drawing.SystemColors.Control;
            this.toolBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.toolBox1.DrawMode = System.Windows.Forms.TreeViewDrawMode.OwnerDrawAll;
            this.toolBox1.FullRowSelect = true;
            this.toolBox1.HotTracking = true;
            this.toolBox1.ImageIndex = 0;
            this.toolBox1.ImageList = this.imageList;
            this.toolBox1.ItemHeight = 18;
            this.toolBox1.LineColor = System.Drawing.Color.White;
            this.toolBox1.Location = new System.Drawing.Point(10, 10);
            this.toolBox1.Name = "toolBox1";
            this.toolBox1.SelectedImageIndex = 0;
            this.toolBox1.ShowLines = false;
            this.toolBox1.ShowNodeToolTips = true;
            this.toolBox1.Size = new System.Drawing.Size(427, 471);
            this.toolBox1.StateImageList = this.imageList;
            this.toolBox1.TabIndex = 8;
            this.toolBox1.NodeMouseDoubleClick += new System.Windows.Forms.TreeNodeMouseClickEventHandler(this.toolBox1_NodeMouseDoubleClick);
            // 
            // Toolbox
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.ClientSize = new System.Drawing.Size(447, 491);
            this.Controls.Add(this.toolBox1);
            this.Font = new System.Drawing.Font("Tahoma", 8F);
            this.HideOnClose = true;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Toolbox";
            this.Padding = new System.Windows.Forms.Padding(10);
            this.ShowHint = WeifenLuo.WinFormsUI.Docking.DockState.DockLeftAutoHide;
            this.TabText = "Toolbox";
            this.Text = "Toolbox";
            this.Load += new System.EventHandler(this.Toolbox_Load);
            this.ResumeLayout(false);

        }
        #endregion

        private System.Windows.Forms.ImageList imageList;
        private VS2005ToolBox.ToolBox toolBox1;
    }
}